import numpy as np

def se3_log(wxyz_xyz: np.ndarray) -> np.ndarray: ...
def se3_inverse_multiply(
    a_wxyz_xyz: np.ndarray, b_wxyz_xyz: np.ndarray
) -> np.ndarray: ...
def se3_rminus(a_wxyz_xyz: np.ndarray, b_wxyz_xyz: np.ndarray) -> np.ndarray: ...
def se3_jlog(wxyz_xyz: np.ndarray) -> np.ndarray: ...
def se3_adjoint(wxyz_xyz: np.ndarray) -> np.ndarray: ...
def se3_rotation_adjoint_from_xmat(xmat: np.ndarray) -> np.ndarray: ...
def se3_inverse(wxyz_xyz: np.ndarray) -> np.ndarray: ...
def xmat_xpos_to_wxyz_xyz(xmat: np.ndarray, xpos: np.ndarray) -> np.ndarray: ...
def se3_frame_task_terms(
    target_wxyz_xyz: np.ndarray, frame_wxyz_xyz: np.ndarray
) -> tuple[np.ndarray, np.ndarray]: ...
def se3_relative_frame_task_terms(
    target_wxyz_xyz: np.ndarray,
    frame_wxyz_xyz: np.ndarray,
    root_wxyz_xyz: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
