name: mink
channels:
    - conda-forge
dependencies:
    - mink
    - pip >=21.3.1
    - pip:
        - sphinx >= 7.2.2
        - sphinx-favicon
        - sphinx-mathjax-offline
        - sphinx_rtd_theme
